location /extras/wifi-wizard/api/ {
    rewrite ^/extras/wifi-wizard(/api/.*)$ $1 break;

    proxy_pass http://wifi_wizard_api;

    include /etc/kvmd/nginx/loc-proxy.conf;
    include /etc/kvmd/nginx/loc-login.conf;
    include /etc/kvmd/nginx/loc-nocache.conf;
}
